apiVersion: v1
kind: ConfigMap
metadata:
  name: promtail-values
  namespace: monitoring-promtail
data:
  README: |
    This file holds example values for the promtail component.
    Replace these with your Helm values or kustomize patches as desired.
