prometheus:
  enabled: true
  prometheusSpec:
    enableFeatures:
      - agent
    agentMode: true
    replicas: 1
    scrapeInterval: 15s
    evaluationInterval: 15s
    retention: 0d
    remoteWrite:
      - url: "https://distances-arg-create-seminar.trycloudflare.com/api/v1/write"
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    probeSelectorNilUsesHelmValues: false
    storageSpec: null

prometheusOperator:
  enabled: true

alertmanager:
  enabled: false

grafana:
  enabled: true
  adminPassword: admin
  service:
    type: NodePort
    nodePort: 30000

kubeStateMetrics:
  enabled: true
nodeExporter:
  enabled: true
