apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-prometheus-stack-values
  namespace: monitoring-kube-prometheus-stack
data:
  README: |
    This file holds example values for the kube-prometheus-stack component.
    Replace these with your Helm values or kustomize patches as desired.
