apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: loki
    repo: https://grafana.github.io/helm-charts
    version: 6.16.4
    releaseName: loki
    namespace: logging
    valuesFile: values.yaml
