apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-values
  namespace: monitoring-loki
data:
  README: |
    This file holds example values for the loki component.
    Replace these with your Helm values or kustomize patches as desired.
